apiVersion: apps/v1
kind: Deployment
metadata:
  name: teun-zengerink-com-app
  labels:
    app: teun-zengerink-com-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teun-zengerink-com-app
  template:
    metadata:
      labels:
        app: teun-zengerink-com-app
    spec:
      containers:
      - name: teun-zengerink-com-app
        image: teunzengerink/teun.zengerink.com:main
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
