apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgi-zengerink-com-app
  namespace: prd
  labels:
    app: pgi-zengerink-com-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgi-zengerink-com-app
  template:
    metadata:
      labels:
        app: pgi-zengerink-com-app
    spec:
      imagePullSecrets:
       - name: dockerhub-secret
      containers:
      - name: pgi-zengerink-com-app
        image: teunzengerink/python-degiro-insights:main
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: FASTAPI_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pgi-zengerink-com-secret
              key: FASTAPI_JWT_SECRET
        - name: FASTAPI_USERNAME
          valueFrom:
            secretKeyRef:
              name: pgi-zengerink-com-secret
              key: FASTAPI_USERNAME
        - name: FASTAPI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgi-zengerink-com-secret
              key: FASTAPI_PASSWORD
