apiVersion: v1
kind: Service
metadata:
  name: pgi-zengerink-com-service
  namespace: prd
spec:
  type: ClusterIP
  selector:
    app: pgi-zengerink-com-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
