apiVersion: v1
kind: Service
metadata:
  name: annekelabordus-nl-service
  namespace: prd
spec:
  type: ClusterIP
  selector:
    app: annekelabordus-nl-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
