apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-domain-ingress
  namespace: prd
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt-issuer"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - teun.zengerink.com
    - www.cyberpeaks.nl
    #- www.annekelabordus.nl
    secretName: multi-domain-tls
  rules:
  - host: teun.zengerink.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teun-zengerink-com-service
            port:
              number: 80
  - host: www.cyberpeaks.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cyberpeaks-nl-service
            port:
              number: 80
  - host: www.annekelabordus.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: annekelabordus-nl-service
            port:
              number: 80
