apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-ingress
spec:
  rules:
  - host: teun.zengerink.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teun-zengerink-com-service
            port:
              number: 80
